name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 4b916fc23fa717029c11d5e1cd766a68
          WAKATIME_API_KEY: waka_8869a937-82ac-4658-817e-ed17b2c1ec7d
